name: image_compressor
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animated_button: ^0.2.0
  flutter_image_compress: ^2.3.0
  image_picker: ^1.1.2
  image_gallery_saver_plus: ^3.0.5
  path_provider: ^2.1.4
  flutter_staggered_grid_view: ^0.7.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  before_after: ^3.1.0
  share_plus: ^10.1.0
  font_awesome_flutter: ^10.7.0
  crop_your_image: ^1.1.0
  permission_handler: ^11.3.1
  file_picker: ^8.1.2
  video_compress_plus: ^1.0.0
  icons_launcher: ^3.0.0
  flutter_lints: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

icons_launcher:
  image_path: "assets/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
